spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=jdbc:mysql://db:3307/blog_app
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=tamerm
spring.datasource.password=tamerm
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always

logging.level.org.springdoc=INFO

jwt.secret=${JWT_SECRET}

spring.jpa.properties.hibernate.search.backend.type=lucene
spring.jpa.properties.hibernate.search.backend.directory.root=./lucene-index
spring.jpa.properties.hibernate.search.schema_management.strategy=create-or-update

app.media.storage-path=${MEDIA_STORAGE_PATH:./media-storage}