spring.application.name=Blog Application

spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=jdbc:h2:mem:blog-app
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=tamerm
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
